version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Entered the install phase...
      - pip install pipenv
      - pipenv install --dev
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pipenv run coverage run --omit "tests/*,application.config" -m unittest
      - pipenv run coverage report
      - pipenv run coverage xml
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build complete on `date`

reports:
  sample-python-web-app-python-reports:
    files:
      - coverage.xml
    file-format: COBERTURAXML